name: Builds

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        config: [Release]
        platform: [Win32, x64]
    
    steps:
    - uses: actions/checkout@v3

    - uses: SpecialKO/GA-setup-cpp@master

    - uses: microsoft/setup-msbuild@v1.1

    - name: Build the Special K source code
      run: |
        msbuild SpecialK.sln -p:Configuration="${{ matrix.config }}" -p:Platform="${{ matrix.platform }}" -m

    - name: Prepare environment variables for the artifact name
      run: |
        $Version = (Get-Item "$HOME\Documents\My Mods\SpecialK\SpecialK*.dll").VersionInfo.ProductVersion
        If ($null -eq $Version) { $Version = "unknown" }
        "SK_VERSION=$Version" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append
        "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" | Out-File -FilePath $env:GITHUB_ENV -Encoding UTF8 -Append

    - uses: actions/upload-artifact@v3
      with:
        name: SpecialK_${{ env.SK_VERSION }}_${{ env.SHORT_SHA }}
        path: |
          ~\Documents\My Mods\SpecialK\*.dll
        if-no-files-found: error

    - uses: actions/upload-artifact@v3
      with:
        name: SpecialK_${{ env.SK_VERSION }}_${{ env.SHORT_SHA }}_debug_symbols
        path: |
          ~\Documents\My Mods\SpecialK\*.pdb
        if-no-files-found: warn
